## Support Vector Machine

## Q1. What is the mathematical formula for a linear SVM?

In [1]:
## The mathematical formula is  y = m*x + c

## Q2. What is the objective function of a linear SVM?

In [2]:
## The objective of linear SVM is to find the best fit line.
## Along with best fit line we need to marginal lines parallel to the best fit line.
## This lines shoud be at maximum distance from each other.

## Q3. What is the kernel trick in SVM?

In [3]:
## Kernel is used to increase the number of dimention.
## If problem has one dimention then two dimentions are created to solve the problem.

## Q4. What is the role of support vectors in SVM Explain with example

In [4]:
## Support vectors are the marginal lines parallel to the best fit line.
## They are use to differentiate between two categories of output.

## Q5. Illustrate with examples and graphs of Hyperplane, Marginal plane, Soft margin and Hard margin in SVM?

In [5]:
## Marginal plane :- this is the plane which is parallel to the best fit plane.
## Hard margin :- none of the datapoints are missclassified
## Soft margin:- some data points are missclassified.

## Q6. SVM Implementation through Iris dataset.

In [6]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [20]:
dataset = load_iris()

In [21]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [24]:
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [26]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [36]:
x = df.iloc[:,:]
y = dataset.target

In [37]:
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [29]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=12)

In [41]:
x_train.shape,x_test.shape

((112, 4), (38, 4))

In [42]:
from sklearn.svm import SVC
svc = SVC()

In [43]:
svc

SVC()

In [44]:
svc.fit(x_train,y_train)

SVC()

In [46]:
y_pred = svc.predict(x_test)

In [47]:
y_pred

array([0, 2, 0, 1, 2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2, 1, 0, 1, 0, 1,
       2, 1, 0, 2, 2, 1, 0, 0, 0, 1, 2, 0, 2, 0, 1, 1])

In [48]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[15  0  0]
 [ 0 11  1]
 [ 0  0 11]]
0.9736842105263158
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.92      0.96        12
           2       0.92      1.00      0.96        11

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



In [49]:
## Accuracy is 97 percent.

In [50]:
svc = SVC()
parameter = {'C':[1,10,100,1000]}
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(SVC(),param_grid=parameter)

In [51]:
grid.fit(x_train,y_train)

GridSearchCV(estimator=SVC(), param_grid={'C': [1, 10, 100, 1000]})

In [52]:
grid.best_params_

{'C': 10}

In [55]:
y_pred = grid.predict(x_test)

In [56]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[15  0  0]
 [ 0 11  1]
 [ 0  0 11]]
0.9736842105263158
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.92      0.96        12
           2       0.92      1.00      0.96        11

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

